apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
  namespace: argocd

spec:
  destination:
    namespace: demo-app
    server: "https://kubernetes.default.svc"

  project: default

  source:
    path: backend-app
    repoURL: "https://github.com/phidvss55/test-infra.git"
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: client-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: "https://github.com/phidvss55/test-infra.git"
#     targetRevision: HEAD
#     path: client-app
#   destination:
#     name: ""
#     namespace: client-app
#     server: "https://kubernetes.default.svc"
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
