# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-app-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 100Mi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  # labels:
  #   app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: phidinh/test-circle-ci:v0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # env:
          #   - name: GIN_MODE
          #     value: "release"
          #   - name: DATA_DIR
          #     value: "/data"
          # volumeMounts:
          #   - name: demo-app-vol
          #     mountPath: /data
      # volumes:
      #   - name: demo-app-vol
      #     persistentVolumeClaim:
      #       claimName: demo-app-pvc
