apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: my-backend-demonstration-description
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app-container
          image: phidinh/test-circle-ci:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          # env:
          #   - name: GIN_MODE
          #     value: "release"
          #   - name: DATA_DIR
          #     value: "/data"
          # volumeMounts:
          #   - name: demo-app-vol
          #     mountPath: /data
      # volumes:
      #   - name: demo-app-vol
      #     persistentVolumeClaim:
      #       claimName: demo-app-pvc
